spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/jr-pricing-local"
    username: root
    password: root
  config:
    activate:
      on-profile: local
  flyway:
    baseline-on-migrate: true
    baseline-version: 1.0.0
    baseline-description: Initial
    locations: classpath:db/migration
logging:
  level:
    root: DEBUG